spring:
  application:
    name: "servicediscovery"
  config:
    import: "configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com:
      goaleaf:
        servicediscovery: DEBUG
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"